### ISSUE TITLE
Local Policy Mode of groups doesn't take effect

### ISSUE THREAD

**Issue by 0Styless** [neuvector/neuvector#1037]
**Environment**
Platform: Kubernetes Rancher / RKE2
Kubernetes/Platform Version(s): v1.25.11+rke2r1
OS: SLES15-SP4
NeuVector Version: 5.2.1 / 2.6.2

**Describe the bug**
The local Policy Mode under **_>> Policy >>> Groups_** doesn't take any effect, only global settings in **_>> Settings >>> Configuration_** are used.

For example, global **Network Security Policy** Mode is set to **Monitor**:

![image](https://github.com/neuvector/neuvector/assets/30753608/b8b3c2b1-f9b9-4767-b24a-9ed516b63991)

But groups in Discovery Mode won't learn any new Network Rules:

![image](https://github.com/neuvector/neuvector/assets/30753608/33a0e3af-f4b2-4574-b297-f040e4a44294)

Instead, there will be a security warning in **_>> Notifications >>> Security Events_**:

![image](https://github.com/neuvector/neuvector/assets/30753608/a2847caa-0d3f-4fc5-8770-100f8b3d8519)

Vice versa is even more dangerous - let's set the global **Network Security Policy** Mode to Discovery:

![image](https://github.com/neuvector/neuvector/assets/30753608/20d543b3-c55b-48a1-a4d6-70185e295586)

But groups in Protect Mode still learning new processes and Network Rules and set them automatically to Allow!:

![image](https://github.com/neuvector/neuvector/assets/30753608/cc32efbb-adc1-4016-9bb2-9d566cd65823)

So there isn't any protection at all!

**Expected behavior**
Global Policy Mode should not affect the Group Policy Mode.

**Comment by williamlin-suse** [comment]
There is no member in the 2nd snapshot. How is the group created? By import from UI? What do you expect for a group without member?
The security warning in >> Notifications >>> Security Events in the 3rd snapshot is from process profile rules, not network policy.
The last snapshot shows another group is created by you thru CRD. Settings specified in CRD override settings defined thru REST API.
"New Services Mode" & "Network Security Policy Mode" are 2 different configurations.
I don't see what's wrong.

**Comment by 0Styless** [comment]
1) I don't know why there wasn't any members at the time of the screenshot, I can ensure there were a deployment of nginx with 3 replicas
2) Group was learned by NV itself - no import, no CRD
3) Pls look close, second entry in Notifications >>> Security Events is a network event
4) What are you trying to tell me with that? Of course, this is a CRD created group by me - but has nothing to do with the fact that the group in Protect mode (which is defined by the CRD) still learn new processes and network rules...

What's wrong: A group in discovery mode should learn new things and a group in monitor or protect mode shouldn't regardless of the global settings for New Service Mode & Network Security Policy Mode.

This can't be work as designed - in which world it is a gain of security if groups in Protect Mode still allow new processes and network communications?

**Comment by williamlin-suse** [comment]
CRD policy rules are evaluated before learned/user-created rules.
Policy Mode for a group is for process/file rules. It's also for the group's network policy rules but could be overridden by Network Security Policy Mode.
Network Security Policy Mode overrides all groups' Policy Mode for network policy rules if it's enabled.
There is no member in the 2nd snapshot. 
So we can assume that group was learned with a workload(container/pod) first & the workload is already gone when the 2nd snapshot is taken.
It really depends on what's the Network Security Policy Mode & New Service mode values before the group is learned.
However, we do see the event in the 3rd snapshot.
The sequence could be:
1. new groups & network policy are learned (Network Security Policy Mode & New Service mode are Discover) 
2. Network Security Policy Mode is changed to Monitor mode
3. the security event is created
4. the workload in the group is gone

In the 4th snapshot, global Network Security Policy Mode is Discovery
In the 5th snapshot, the CRD group is Protect mode which is for process/file rules only.
So the CRD group keeps learning network policy rule but not process/file rules. 
The 5th snapshot doesn't show whether any process/file rule is learned after the CRD group is created

**Comment by 0Styless** [comment]
THANKS A LOT for this explanation!
I was not aware that the global setting overrides the policy mode of the groups for network policies.

Let me ask one last question. What about this: 

![image](https://github.com/neuvector/neuvector/assets/30753608/8143a206-bb78-4833-94d2-aa103510352b)

I can see that new processes (like `ls` or `sh`) are blocked as expected, but no matter how often I delete the learned `cat` rule, it still comes back, at latest when the pod restarts. I guess as long it is no new process it's fine, but I would like to understand why this happens.

CRD that is deployed for the group:

```yaml
---
apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.kubernetes-event-exporter.managed-services
    namespace: managed-services
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: allow
      applications:
      - SSL
      name: external-egress-0
      ports: tcp/6443
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: kube-apiserver-master.kube-system
        - key: domain
          op: =
          value: kube-system
        name: nv.kube-apiserver-master.kube-system
        original_name: ""
    file: []
    ingress: []
    process:
    - action: allow
      allow_update: false
      name: cat
      path: "*"
    - action: allow
      allow_update: false
      name: kubernetes-event-exporter
      path: /opt/bitnami/kubernetes-event-exporter/bin/kubernetes-event-exporter
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    process_profile:
      baseline: basic
    target:
      policymode: Protect
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: kubernetes-event-exporter.managed-services
        - key: domain
          op: =
          value: managed-services
        name: nv.kubernetes-event-exporter.managed-services
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
````
