### ISSUE TITLE
Rancher Continous Delivery

### ISSUE THREAD

**Issue by hwaastad** [neuvector/neuvector#108]
**Is your feature request related to a problem? Please describe.**
This is maybe a request for documentation rather than a feature request

**Describe the solution you'd like**
Rancher Continuous Delivery (Fleet) has a few challenges when it comes to discovery and protection.
It would be nice to have documentation on how to handle fleet deployments
Every new commit to gitrepo will create a new k8s job with a unique name <gitrepo>-<unique id>

**Describe alternatives you've considered**
I have tried to create a default group matching on namespace fleet-local/and fleet-default and giving process rules and network policies but it seem I cannot get it working 100% especially when default new services are in protected mode. security events occurs.

**Comment by garyduan** [comment]
Fleet is a multi-cluster management function to my understanding. Is the intent to create security policy whenever a service is deployed in the managed cluster? Or is it about a particular workflow that make it smoother?

**Comment by hwaastad** [comment]
Hi @garyduan, yes. And Rancher will use fleet for system-upgrades amongst others.
Iin master cluster a new nv group will be created on every commit. 
Currently, I've made a general group with domain=fleet-local || fleet-default && service=gitrepo* and I think its working, but I still get events for some processes. 
An example, I have a gitrepo called neuvector
The Security Event:
```
Process Parent Name:  runc    Process Parent Path:  /run/torcx/unpack/docker/bin/runc    Process Name:  pause    Process Path:  /pause    Process Command:     /pause    Process Effective UID:  1000
```
the general rule applied:
```yaml
apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: fleet-demo.fleet-default
    namespace: fleet-local
  spec:
    egress:
    - action: allow
      applications:
      - DNS
      name: nv.coredns.kube-system-egress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: kube-system
        - key: service
          op: =
          value: coredns.kube-system
        name: nv.coredns.kube-system
        original_name: ""
    - action: allow
      applications:
      - any
      name: nv.rancher:hyperkube-egress-1
      ports: tcp/6443
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: rancher/hyperkube
        name: nv.rancher:hyperkube
        original_name: ""
    file: []
    ingress: []
    process:
    - action: allow
      allow_update: false
      name: basename
      path: /bin/busybox
    - action: allow
      allow_update: false
      name: busybox
      path: /bin/busybox
    - action: allow
      allow_update: false
      name: entrypoint
      path: /tekton/tools/entrypoint
    - action: allow
      allow_update: false
      name: env
      path: /bin/busybox
    - action: allow
      allow_update: false
      name: fleet
      path: /usr/bin/fleet
    - action: allow
      allow_update: false
      name: git
      path: /usr/bin/git
    - action: allow
      allow_update: false
      name: git
      path: /usr/libexec/git-core/git
    - action: allow
      allow_update: false
      name: git-init
      path: /usr/bin/git-init
    - action: allow
      allow_update: false
      name: git-remote-https
      path: /usr/libexec/git-core/git-remote-https
    - action: allow
      allow_update: false
      name: git-sh-i18n--en
      path: /usr/libexec/git-core/git-sh-i18n--envsubst
    - action: allow
      allow_update: false
      name: git-sh-i18n--envsubst
      path: /usr/libexec/git-core/git-sh-i18n--envsubst
    - action: allow
      allow_update: false
      name: git-submodule
      path: /bin/busybox
    - action: allow
      allow_update: false
      name: log.sh
      path: /bin/bash
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    - action: allow
      allow_update: false
      name: sed
      path: /bin/busybox
    - action: allow
      allow_update: false
      name: sh
      path: /bin/busybox
    - action: allow
      allow_update: false
      name: tee
      path: /bin/busybox
    - action: allow
      allow_update: false
      name: uname
      path: /bin/busybox
    process_profile:
      baseline: default
    target:
      policymode: N/A
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: fleet-default
        - key: domain
          op: =
          value: fleet-local
        - key: service
          op: =
          value: neuvector*
        name: fleet-demo.fleet-default
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
```

As I mentioned, this is maybe a suggestion for extra documentation when the integration with Rancher is coming along. Since running in discovery mode will only identify group matching on the exact service and on next commit (and running in protected mode) this group will not match.
