### ISSUE TITLE
Configmap Settings are not applied

### ISSUE THREAD

**Issue by 0Styless** [neuvector/neuvector#1104]
**Environment**
Platform: Rancher
Kubernetes/Platform Version(s): v1.25.15+rke2r2
NeuVector Version: 5.2.3

**Describe the bug**
According to your documentation:

> The persistent storage configuration backup is read first, then the ConfigMaps are applied, so ConfigMap settings take precedence. All ConfigMap settings (e.g. updates) will also be saved into persistent storage.

https://open-docs.neuvector.com/deploying/production/configmap#configmaps-and-persistent-storage

Deployment of a new Cluster with NeuVector does not apply settings from configmaps.

**To Reproduce**

1. create configmap ini-neuvector with various settings, for example:

```yaml
apiVersion: v1
data:
  passwordprofileinitcfg.yaml: |
    always_reload: true
    active_profile_name: default
    pwd_profiles:
    - name: default
      comment: Default-Setting
      min_len: 12
      min_uppercase_count: 1
      min_lowercase_count: 1
      min_digit_count: 1
      min_special_count: 1
      enable_block_after_failed_login: true
      block_after_failed_login_count: 2
      block_minutes: 1
      enable_password_expiration: false
      password_expire_after_days: 0
      enable_password_history: false
      password_keep_history_count: 0
      session_timeout: 3600
  roleinitcfg.yaml: |
    always_reload: true
    roles:
    - Comment: Admin role for downstream clusters
      Name: OUAdmin
      Permissions:
        - id: vulnerability
          read: true
          write: true
        - id: config
          read: true
          write: true
        - id: rt_scan
          read: true
          write: true
        - id: reg_scan
          read: true
          write: true
        - id: ci_scan
          read: true
          write: true
        - id: rt_policy
          read: true
          write: true
        - id: admctrl
          read: true
          write: true
        - id: compliance
          read: true
          write: true
        - id: audit_events
          read: true
        - id: security_events
          read: true
        - id: events
          read: true
        - id: authentication
          read: false
          write: false
        - id: authorization
          read: false
          write: false
  sysinitcfg.yaml: |
    always_reload: true
    New_Service_Policy_Mode: Discovery
    New_Service_Profile_Baseline: basic
    Auth_By_Platform: false
    Cluster_Name: my-super-cool-cluster
    Monitor_Service_Mesh: true
    Registry_Http_Proxy_Status: false
    Registry_Https_Proxy_Status: false
    Registry_Http_Proxy:
      URL: http://...
    Registry_Https_Proxy:
      URL: http://...
    Xff_Enabled: true
    Net_Service_Status: false
    Net_Service_Policy_Mode: Monitor
    Scanner_Autoscale:
      Strategy: delayed
      Min_Pods: 2
      Max_Pods: 5
    No_Telemetry_Report: true
    Scan_Config:
      Auto_Scan: true
    Unused_Group_Aging: 48
kind: ConfigMap
metadata:
  name: neuvector-init
  namespace: neuvector
  ```

2. Deploy NeuVector
3. Check configuration inside NeuVector UI (nothing is configured, Cluster name is still cluster.local, ...)
4. Configmaps are loaded as expected (in controller pods: `cat /etc/config/sysinitcfg.yaml` for example)

**Expected behavior**

Init-configuration from configmaps should be applied to NeuVector configuration.

**Screenshots**
![image](https://github.com/neuvector/neuvector/assets/30753608/9801bcfa-e0bb-46cd-b1f1-844b2da49365)
