### ISSUE TITLE
[docker compose] neuvector/allinone does not persist changes

### ISSUE THREAD

**Issue by ngoeddel-openi** [neuvector/neuvector#1204]
**Environment**
Platform: docker compose
Docker compose Version(s): 2.20.2+ds1-0ubuntu1~22.04.1
neuvector/allinone version: 5.3.0

**Describe the bug**
Although the directory `/var/neuvector` is mounted with write permissions to the host, Neuvector does not store anything there.
This means that everything I change during the runtime of the container gets lost after a restart. This includes setting the admin password.

**To Reproduce**
1. Execute `docker compose up -d`
2. Wait a a few minutes until the UI is ready.
3. Login, change the password of the `admin` user.
4. Execute `docker compose down`
5. Execute `docker compose up -d`
6. The password of the `admin` user is reset to the default again.

**Expected behavior**
I expected persistence of all the changes I made to Neuvector and that they get stored in `/var/neuvector`. Instead the directory remains empty.

**Screenshots**
Here's the view of the directory `/var/neuvector` inside the container:
```
/ # whoami
root
/ # hostname
65efadbac180
/ # ls -la /var/neuvector
total 0
drwxrwxrwx    2 5006     5006             6 Jan 26 17:20 .
drwxr-xr-x    1 root     root            23 Feb  9 11:06 ..
```
And here's from the outside:
```
harbor@example:~/git/neuvector$ whoami
harbor
harbor@example:~/git/neuvector$ ls -la ./neuvector
total 0
drwxrwxrwx 2 harbor harbor  6 Jan 26 18:20 .
drwxrwxr-x 3 harbor harbor 86 Feb  8 18:32 ..

```

**Additional context**
*`docker-compose.yml`*:
```yaml
name: neuvector

networks:
  neuvector:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NEUVECTOR_SUBNET}
    driver_opts:
      com.docker.network.bridge.name: d-neuvector
  app_harbor:
    external: true

services:
  allinone:
    pid: host
    image: neuvector/allinone:${NEUVECTOR_VERSION:-latest}
    restart: always
    container_name: neuvector.allinone
    deploy:
      mode: global
    networks:
      neuvector:
        ipv4_address: ${NEUVECTOR_IP_ALLINONE}
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
      - IPC_LOCK
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
      - label=disable
    environment:
      - CLUSTER_JOIN_ADDR=${NEUVECTOR_IP_ALLINONE}
      - NV_PLATFORM_INFO=platform=Docker
    ports:
      - 18300:18300
      - 18301:18301
      - 18400:18400
      - 18401:18401
      - 18301:18301/udp
      - 8443:8443
    volumes:
      - /lib/modules:/lib/modules:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/cgroup:ro
      - ./neuvector:/var/neuvector
      # See https://open-docs.neuvector.com/configuration/console/replacecert
      - /home/harbor/certs/example.com.key:/etc/neuvector/certs/ssl-cert.key:ro
      - /home/harbor/certs/example.com.crt:/etc/neuvector/certs/ssl-cert.pem:ro
```
*`.env`*:
```
# Find the latest versions here: https://hub.docker.com/r/neuvector/allinone/tags
NEUVECTOR_VERSION=5.3.0
NEUVECTOR_SUBNET=172.75.0.0/24
NEUVECTOR_IP_ALLINONE=172.75.0.2
NEUVECTOR_IP_ADAPTER=172.75.0.4
```
