### ISSUE TITLE
Export & Import CRD Host network rules fail

### ISSUE THREAD

**Issue by brightdroid** [neuvector/neuvector#1256]
**Environment**
Kubernetes/Platform Version(s): k3s v1.28.7+k3s1
Neuvector Helm Chart: 2.7.3

**Describe the bug**
For deployments with specific host network rules (ingress) the export skips these roles with following message in controller-logs:
> ERRO|CTL|rest.exportAttachRule: Skip special group export - name=Host:x.x.x.x

Also I can't import CRD rules with following rules (excerpt):
```yaml
spec:
  ingress:
    - action: allow
      name: ccu
      ports: tcp/80
      selector:
        name: Host:x.x.x.x
```
fails to import with this error:
> ERRO|CTL|rest.validateGroupConfig: Cannot use reserved name - name=Host:x.x.x.x

**To Reproduce**
1. Create Ingress Rule with Host:x.x.x.x
2. Export Group
3. View Group and notice the missing Host:... rule
4. See logs of deployment/neuvector-controller-pod

**Expected behavior**
Export should include Host:... rules and CRD should import
