### ISSUE TITLE
Admission Control Issue with regex and ranges

### ISSUE THREAD

**Issue by frjaraur** [neuvector/neuvector#1284]
**Environment**
Platform: RKE2
Kubernetes/Platform Version(s): 1.24.16

**Describe the bug**
I followed the example published in https://www.suse.com/support/kb/doc/?id=000021230 and it seems that it doesn't work added in a deny rule:
```
  rules:
  - action: deny
    comment:  DENY UIDs and GUIDs not in range 25000-90000
    containers:
    - containers
    criteria:
    - name: namespace
      op: notContainsAny
      path: namespace
      value: reccetool,flexi,catalog3d,procurement,smi-backend
    - name: user
      op: '!regexContainsAny'
      path: user
      value: (2500[0-9]|250[1-9][0-9]|25[1-9][0-9]{2}|2[6-9][0-9]{3}|[3-5][0-9]{4}|6[0-4][0-9]{3}|65000)
    disabled: false
    rule_mode: monitor
```

I am running the following deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nonroot
  name: nonroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nonroot
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nonroot
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 80001
      containers:
      - args:
        - sleep
        - INF
        image: docker.io/busybox:1.35
        name: busybox
        resources: {}
```

Neuvector shows a validation warning (in audit mode)
```
2024-04-08 16:41:33.244 | {   "notification": "audit",   "name": "Admission.Control.Violation",   "level": "Warning",   "reported_timestamp": 1712587292,   "reported_at": "2024-04-08T14:41:32Z",   "cluster_name": "k8scs",   "host_id": "",   "host_name": "",   "enforcer_id": "",   "enforcer_name": "",   "workload_domain": "testing",   "workload_image": "docker.io/busybox:1.35",   "high_vul_cnt": 0,   "medium_vul_cnt": 0,   "message": "Update of Kubernetes Deployment resource (nonroot) violates Admission Control deny rule id 1006 but is allowed in per-rule monitor mode [Notice: the requested image(s) are not scanned: docker.io/busybox:1.35]",   "user": "u-bodrdcvqqf",   "aggregation_from": 1712587292,   "count": 1 }
```

**To Reproduce**
I have just followed the instructions in https://www.suse.com/support/kb/doc/?id=000021230 and used a  '!regexContainsAny' matching criteria.

**Expected behavior**
The deployment should pass the validation correctly as we are using the user 80001 in this example.

Please let us know if we are configuring something wrong.

**Comment by becitsthere** [comment]
As the log message indicates, the violation is on the rule 1006, not 80001. It is in the monitor mode.

**Comment by frjaraur** [comment]
Yes, we are using monitor mode to don't disrupt the actual services, but no, the 1006 id indicates de rule violated, not the 80001 uid. "the violation is on the rule 1006, not 80001" does not make any sense here. The violation always identifies the rule violated.

**Comment by becitsthere** [comment]
I probably missed something here. I don't see that we are complaining that rule 80001 is wrong, so what is the issue?

**Comment by frjaraur** [comment]
Well in fact, the message doesn't say anything about rule 80001...
"Update of Kubernetes Deployment resource (nonroot) violates Admission Control deny rule id 1006 but is allowed in per-rule monitor mode [Notice: the requested image(s) are not scanned: docker.io/busybox:1.35]"

Sorry because I forgot to tell you that the current rule described in https://www.suse.com/support/kb/doc/?id=000021230 does not do what the text says "Let`s suppose we want to create an Admission Control Rule with a range of 65,000 users.  The first user will be 25000, and the last user will be 90000." In fact, the rule allows users between 25000 and 65000, which will correctly should trigger an error when a userID out of the range is used (in this case 80001). The problem comes when the userID 30000 is not allowed either.
```
% cat nonroot.deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nonroot
  name: nonroot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nonroot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nonroot
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 30000
      containers:
      - args:
        - sleep
        - INF
        image: docker.io/busybox:1.35
        name: busybox
        resources: {}
```

I just replaced the current deployment:
```
% kubectl replace -f nonroot.deploy.yaml
deployment.apps/nonroot replaced
```
And following alarm is triggered:
```
Update of Kubernetes Deployment resource (nonroot) violates Admission Control deny rule id 1006 but is allowed in per-rule monitor mode [Notice: the requested image(s) are not scanned: docker.io/busybox:1.35]
```
Which clearly indicates that neither userID 80001 nor 30000 are allowed, and the rule isn't working properly.
