### ISSUE TITLE
NvClusterSecurityRule is not loaded/activated at runtime

### ISSUE THREAD

**Issue by pbloed** [neuvector/neuvector#1298]
**Environment**
Platform: Openshift 4.13.34/kubernetes 1.26/Neuvector 5.3.1/Chart 2.7.4

**Describe the bug**
When a NvClusterSecurityRule object is created in the neuvector namespace the NvClusterSecurityRule is not loaded in Neuvector.
A controller pod restart is required to activate the change.

**To Reproduce**
1. Create demo.yaml
```yaml
apiVersion: neuvector.com/v1
kind: NvClusterSecurityRule
metadata:
  name: demo
  namespace: ""
spec:
  egress: null
  file: null
  ingress: null
  process: null
  target:
    selector:
      criteria:
      - key: address
        op: =
        value: 0.0.0.0/16
      name: world
```
2. Create kubernetes object
```bash
oc create -n neuvector -f demo.yaml
```

3. Login Neuvector UI en check if network rule is created

4. Restart controller pod and check log for "nvclustersecurityrules"

**Expected behavior**
NvClusterSecurityRule is loaded and activated without a controller restart and the Cluster Security Rule is added at runtime.

**Logging**
No log line(s) when creating the object but after restarting controller pod.
```
2024-04-11T14:24:16.759|INFO|CTL|rest.CrossCheckCrd: - kvCrdKind=NvSecurityRule kvOnly=false len(objs)=1 len(recordList)=0 rscType=nvclustersecurityrules
```
