### ISSUE TITLE
Neuvector Admission Control Policies using "Image registry" do not validate initContainers image registries.

### ISSUE THREAD

**Issue by frjaraur** [neuvector/neuvector#1463]
**Environment**
Platform: Rancher Managed RKE2 environment with Neuvector 5.3.0 running with Admission Control enabled and using "Protect" as Global Mode.

**Describe the bug**
Neuvector Admission Control Policies using "Image registry" do not validate initContainers image registries.

**To Reproduce**
I have created the following rule (copy&paste from export):
```
apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
spec:
  rules:
  - action: deny
    comment: DENY unknown registries not in the list
    containers:
    - containers
    criteria:
    - name: imageRegistry
      op: notContainsAny
      path: imageRegistry
      value: https://myregistry1.mydomain.test/,https://myregistry2.mydomain.test/
    disabled: false
    rule_mode: ""
```
Global Mode is configured to "Protect".

Following Pod is able to run in this cluster where Neuvector 5.3.0 is running.

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    testing: "true"
    project: mytestpod
  name: mytestpod
spec:
  containers:
  - image: myregistry2.mydomain.test/myapp:1.0.0-dev
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 25
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 1
    name: myappt
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      runAsGroup: 7000
      runAsNonRoot: true
      runAsUser: 7000
  imagePullSecrets:
  - name: registry-common-pull
  initContainers:
  - command:
    - sh
    - -c
    - sleep 5
    image: alpine
    imagePullPolicy: Always
    name: initcontainer
    securityContext:
      runAsGroup: 7000
      runAsNonRoot: true
      runAsUser: 7000
  restartPolicy: Always
  serviceAccount: default
  serviceAccountName: default
```
Using a custom rule doesn't work either:
```
apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
spec:
  rules:
  - action: deny
    comment: DENY unknown registries not in the list (ADVANCED)
    containers:
    - containers
    criteria:
    - name: customPath
      op: notContainsAny
      path: item.spec.initContainers[_].image
      type: customPath
      value: myregistry1.mydomain.test,myregistry2.mydomain.test
      value_type: string
    - name: customPath
      op: notContainsAny
      path: item.spec.containers[_].image
      type: customPath
      value: myregistry1.mydomain.test,myregistry2.mydomain.test
      value_type: string
    - name: customPath
      op: notContainsAny
      path: item.spec.ephemeralContainers[_].image
      type: customPath
      value: myregistry1.mydomain.test,myregistry2.mydomain.test
      value_type: string
    disabled: false
    rule_mode: protect
```

**Expected behavior**
Registry policy shouldn't allow the initContainer as it does not contain the defined registry strings.
