### ISSUE TITLE
Scanner cannot scan for host

### ISSUE THREAD

**Issue by tientmse62290** [neuvector/neuvector#1490]
**Environment**
Platform: K8S RKE2 & Docker Native
Kubernetes/Platform Version(s): RKE2 v1.27.12r1 / Docker version 24.0.7, build afdd53b
NeuVector version: v5.3.3

**Describe the bug**
Separate scanners cannot scan for host vulnerability. When hover on the "failed" status appear the description "timeout"
![image](https://github.com/user-attachments/assets/9ad19bbd-eee9-4ab4-be92-3825fc745154)
More from K8S env:
![2024-08-05 20_12_55 - K8S_1](https://github.com/user-attachments/assets/d472e106-07ee-4dfe-beda-fd1b57e0777d)
![2024-08-05 20_12_55 - K8S_2](https://github.com/user-attachments/assets/37b7f6a7-1bf5-43c5-b811-d23fefd057a7)
![2024-08-05 20_12_55 - K8S_3](https://github.com/user-attachments/assets/de261075-8798-4c28-a335-92e7bf9b2e8f)

All containers are scanned but not hosts.
The host that I run allinone (with sample compose file on opendoc) is normal:
![image](https://github.com/user-attachments/assets/ca1557d0-cd3b-4008-aba1-b0b5d5a97fb5)

**To Reproduce**
Steps to reproduce the behavior on Docker:

docker-compose.yaml:
```
version: '3'

services:
  Scanner:
   image: neuvector/scanner:latest
   container_name: scanner
   privileged: true #add more but nothing changed
   pid: host #add more but nothing changed
   environment:
     - CLUSTER_JOIN_ADDR=192.168.105.5
     - CLUSTER_ADVERTISED_ADDR=10.1.0.4
   ports:
     - 18402:18402
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
   restart: always
  enforcer:
    pid: host
    image: neuvector/enforcer:5.3.3
    container_name: enforcer
    privileged: true
    environment:
        - CLUSTER_JOIN_ADDR=192.168.105.5
        - NV_PLATFORM_INFO=platform=Docker
    ports:
        - 18301:18301
        - 18401:18401
        - 18301:18301/udp
    volumes:
        - /lib/modules:/lib/modules:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc:/host/proc:ro
        - /sys/fs/cgroup/:/host/cgroup/:ro
    restart: always
```

**Expected behavior**
Vulnerability information for both host and running containers

Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome / edge
 - Version: latest version

I see the different on the Linux kernel. Is it a factor?
Thank you a lot
