### ISSUE TITLE
Notifications not working after node reboot when using Cilium GatewayAPI/Ingress

### ISSUE THREAD

**Issue by hwaastad** [neuvector/neuvector#1674]
**Environment**
Platform: Rancher RKE2, Cilium 1.16.4, Neuvector 5.4.1

**Describe the bug**
Cilium has in a couple of versions back added an "ingress" endpoint. Running Gateway API, either with BGP Controller, LBIpam or GatewayAPI and Hostport, neuvector will, on discovery, see external traffic coming in as:
1. External
2. Unmanaged Workload:[ingress ip]

The IP used for the ingress endpoint is found in:
ciliumnode.spec.ingress.ipv4

The issue here is that this IP address changes after node reboot so the incoming traffic will have a new source, hence the already existing permit rule will not work

**To Reproduce**
1. Install cilium (kube-proxy-less) with GatewayAPI, Gateway and HTTPRoute to a exposed service. (as far as I can see it does not matter if bpf.masquerade is enabled or not), native routing, autoDirectNodeRoutes: true, bpf.hostLegacyRouting: true,endpointRoutes.enabled: true)
3. Run NV in discovery mode, create an allowed group, remove external, set protected mode.
4. Run curl -vvv -H "Host: [fqdn]" -H "X-Forwarded-For: [allowed ip]" http://[gateway-ip][gateway-port]
5. Verfify OK
6. Run curl -vvv -H "Host: [fqdn]" -H "X-Forwarded-For: [not-allowed-ip]" http://[gateway-ip]:[gateway-port]
7. Verify traffic blocked and entry in Security Events
8. Reboot nodes
9. Run nbr 3
10. Verify OK
11. Run nbr 5
12. Verify Traffic blocked, but no entry in Security Events

**Expected behavior**
I would expect Notification being sent after reboot

**Additional context**
There might be som corner cases but modifying cilium bpf/loadbalancing.acceleration is not consistent during my tests.
I do not know if it is possible to make the ingress IP persistent over reboots.
Maybe in some way process this ingress IP?

**Comment by hwaastad** [comment]
Just a bit more details about cilium configuration:
```
autoDirectNodeRoutes: true
bpf:
  hostLegacyRouting: false
  masquerade: true
endpointRoutes:
  enabled: false
envoy:
  enabled: false
gatewayAPI:
  enableAlpn: false
  enableAppProtocol: false
  enableProxyProtocol: false
  enabled: true
  externalTrafficPolicy: Cluster
  gatewayClass:
    create: auto
  hostNetwork:
    enabled: true
    nodes:
      matchLabels:
        node-role.kubernetes.io/ingress: 'true'
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sServiceHost: [api-lb]
k8sServicePort: '6443'
kubeProxyReplacement: true
loadBalancer:
  acceleration: native
  l7:
    algorithm: round_robin
    backend: envoy
    ports: []
  mode: snat
routingMode: native

```
I also noticed that if I redeploy app (kubectl delete -> delete all groups -> kubectl apply), I have to restart enforcers to get XFF processed. If I do'nt, only ingress is shown as source for traffic (discovery mode)
