### ISSUE TITLE
404 page not found & internal error while integrating Neuvector with Harbor

### ISSUE THREAD

**Issue by idogancay** [neuvector/neuvector#1690]
I’m working on integrating Neuvector with Harbor but im a bit stuck. I will explain what I have done so far. In addition, I followed this documentation: https://open-docs.neuvector.com/scanning/registry/harbor/#scanning-harbor-registries-using-the-pluggable-scanner.

## Robot Account
I created a robot account named _robot$neuvector_ and temporarily granted all permissions for all projects. Using the same credentials, I created a secret within the Neuvector namespace.

```
apiVersion: v1
kind: Secret
metadata:
  name: neuvector-registry-adapter
  namespace: neuvector
data:
  username: cm9ib3QkbmV1dmVjdG9yCg==
  password: <password in base64>
```

This secret is also included in Neuvector’s values file.

```
cve:
    adapter:
      enabled: true
      certificate:
        secret: neuvector-https-cert
        keyFile: tls.key
        pemFile: tls.crt
      harbor:
        protocol: https
        secretName: neuvector-registry-adapter
```

## NodePort
The registry adapter is accessible via a NodePort. Below, I have tested the connection. If I use an invalid NodePort, the connection fails. When the correct NodePort is used, the connection is established, but I receive a "404 page not found" error.

**Correct NodePort**
```
$ curl https://neuvector-route-registry-adapter-neuvector.<FQDN>:31149/endpoint
404 page not found
```

**Invalid NodePort**
```
$ curl https://neuvector-route-registry-adapter-neuvector.<FQDN>:31148/endpoint
curl: (7) Failed to connect to neuvector-route-registry-adapter-neuvector.<FQDN> port 31148: Connection refused
```

Is 404 page not found an expected behavior? I don't think so.

## Adding Neuvector as a Scanner in Harbor
When I attempt to add Neuvector as a scanner in Harbor, I receive an internal server error. I also tested using the admin user instead of the robot account, but it did not resolve the issue.

![Screenshot 2024-12-09 at 16 01 27](https://github.com/user-attachments/assets/c36b4a3a-3415-447a-a114-6d5d7bfe7ef4)

Am I missing something? Who can help me?
