### ISSUE TITLE
Issues with Fresh Installation of Version 5.4.2 - Internal Certificates

### ISSUE THREAD

**Issue by idogancay** [neuvector/neuvector#1766]
**Description:**  

I am experiencing issues after performing a fresh installation of NeuVector version 5.4.2, specifically with internal certificate handling. Below are the details:

### Steps Taken:  
1. I followed the documentation instructions for a fresh installation using Helm, enabling `internal.autoGenerateCert` and `internal.autoRotateCert` as specified.  
2. The installation appears successful, and logs indicate that internal certificates were created automatically:  

**Scanner logs:**  
```
2025-01-28T10:01:55|MON|Start scanner, pid=7
2025-01-28T10:01:55.371|INFO|SCN|main.main: start initializing k8s internal secret controller and wait for internal secret creation if it's not created
2025-01-28T10:01:55.406|INFO|SCN|migration.(*InternalSecretController).ReloadSecret: internal certificate is not ready yet.
2025-01-28T10:04:07.004|INFO|SCN|migration.(*InternalSecretController).secretUpdate: Internal secret is up-to-date - rev=401581102
2025-01-28T10:04:07.092|INFO|SCN|migration.InitializeInternalSecretController: cache is synced and internal cert is ready
2025-01-28T10:04:07.092|INFO|SCN|main.main: internal certificate is initialized
```

**Cert upgrader job logs:**  
```
time="2025-01-28T10:04:34Z" level=info msg="All controller coming from the same replica set, but secret is already initialized.  Node failure or controllers are scaled to zero?"
time="2025-01-28T10:04:34Z" level=info msg="No need to update secret"
```

The `neuvector-internal-certs` secret was also successfully created:  
```
NAME                            TYPE                                  DATA   AGE
neuvector-internal-certs        Opaque                                9      20m
```

### Issue:  
Despite this, the GUI is inaccessible. The logs from the manager pod show an error related to certificate validation:  

**Manager pod logs:**  
```
2025-01-28 10:25:22,737|INFO |MANAGER|com.neu.web.Rest$(sslContext:29): Import manager's certificate and private key to manager's keystore
2025-01-28 10:25:22,854|ERROR|MANAGER|org.apache.pekko.actor.OneForOneStrategy(applyOrElse$$anonfun$1:89): Certificate chain is not valid
org.apache.pekko.actor.ActorInitializationException: pekko://manager-system/system/Materializers/StreamSupervisor-0/TLS-for-flow-3-1: exception during creation, root cause message: [Certificate chain is not valid]
```

This suggests an issue with the internal certificate chain, even though the secret appears to have been generated and initialized correctly.

### Additional Questions:  
1. The documentation states:  
   > "For current users with versions prior to 5.4.2, the certificate will remain available in the neuvector/scanner:latest until March 31, 2025. After this date, it will be removed."  

   Does this mean that versions earlier than 5.4.2 will cease to function without action after this date, or does this only apply to users upgrading to 5.4.2 or later?  

2. Could you clarify why the GUI is failing even though the internal certificates seem to be generated as expected during a fresh installation?  

Thank you for your assistance!

**Comment by venkateshjayagopal** [comment]
@idogancay Can you please provide the HELM command you used to deploy the NV on your cluster?. Thanks.

**Comment by idogancay** [comment]
@venkateshjayagopal 

We use ArgoCD to deploy NeuVector with corresponding values.yaml, so no separate helm commands. When I downgrade everything to 5.4.1 everything works fine, with 5.4.2 it goes wrong.

**Comment by idogancay** [comment]
This is the values.yaml:

```
---
# yamllint disable rule:comments-indentation
crd:
  openshift: true

monitor:
  exporter:
    enabled: false

core:
  openshift: true
  registry: <internal registry>
  tag: 5.4.2
  internal:
    autoGenerateCert: true
    autoRotateCert: true
# -------------------------------------------------------------
  controller:
# -------------------------------------------------------------
    pvc:
      enabled: true
      existingClaim: pvc-neuvector
    federation:
      mastersvc:
        type: NodePort
        nodePort: 32001
        route:
          enabled: true
          termination: passthrough
      managedsvc:
        type: NodePort
        nodePort: 32002
        route:
          enabled: true
          termination: passthrough
    certificate:
      secret: neuvector-https-cert
      keyFile: tls.key
      pemFile: tls.crt
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    resources:
      limits:
        cpu: 2000m
        memory: 10Gi
      requests:
        cpu: 100m
        memory: 2280Mi
# -------------------------------------------------------------
  enforcer:
# -------------------------------------------------------------
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        value: "true"
    resources:
      limits:
        cpu: 600m
        memory: 2792Mi
      requests:
        cpu: 100m
        memory: 1Mi
# -------------------------------------------------------------
  manager:
# -------------------------------------------------------------
    svc:
      type: ClusterIP
    route:
      termination: passthrough
    certificate:
      secret: neuvector-https-cert
      keyFile: tls.key
      pemFile: tls.crt
    env:
      ssl: true
    resources:
      limits:
        cpu: 400m
        memory: 2792Mi
      requests:
        cpu: 100m
        memory: 2280Mi
    nodeSelector:
      node-role.kubernetes.io/infra: ""
# -------------------------------------------------------------
  cve:
    updater:
# -------------------------------------------------------------
      schedule: "0 19 * * *"
      nodeSelector:
        node-role.kubernetes.io/infra: ""
# -------------------------------------------------------------
    scanner:
# -------------------------------------------------------------
      replicas: 3
      resources:
        limits:
          cpu: 400m
          memory: 2792Mi
        requests:
          cpu: 100m
          memory: 1Gi
      nodeSelector:
        node-role.kubernetes.io/infra: ""
# -------------------------------------------------------------
  crio:
    enabled: true
  crdwebhook:
    enabled: false

```

**Comment by venkateshjayagopal** [comment]
One quick question, was these certificates internally generated?. 

```
 certificate:
      secret: neuvector-https-cert
      keyFile: tls.key
      pemFile: tls.crt
```
