### ISSUE TITLE
Quick processes can bypass rules

### ISSUE THREAD

**Issue by msnominet** [neuvector/neuvector#1800]
**Environment**
Platform: EKS
Kubernetes/Platform Version(s):  1.31, neuvector 5.4.2

**Describe the bug**
We have noticed that very quick running jobs, do not appear to register to any group, and do not block, even if there is a valid rule. By increasing the sleep time, to roughly five seconds, rules start to be applied. This means that an attacker can violate any rule, if they are quick enough.

**To Reproduce**
1.  Create namespace example
2.  create group that includes namespace example, and a rule that blocks all traffic
for reference here is the CR I use
```
apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvClusterSecurityRule
  metadata:
    name: badsite
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: deny
      applications:
      - any 
      name: external-egress-bad-site-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: external
        original_name: ""
    - action: allow
      applications:
      - any
      name: nv.coredns.kube-system-egress-badsite-1
      ports: tcp/53,udp/53
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: kube-system
        - key: service
          op: =
          value: coredns.kube-system
        name: nv.coredns.kube-system
        original_name: ""
    file: []
    ingress: []
    process: []
    target:
      policymode: N/A 
      selector:
        comment: ""
        criteria:
        - key: app
          op: =
          value: badsite
        - key: namespace
          op: =
          value: example
        grp_band_width: 0
        grp_sess_cur: 0
        grp_sess_rate: 0
        mon_metric: false
        name: badsite
        original_name: ""
    waf:
      settings:
      - action: deny
        name: bad-website
      status: true
kind: List
metadata: {}
---
apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvWafSecurityRule
  metadata:
    creationTimestamp: null
    name: bad-website
  spec:
    sensor:
      comment: detect bad website
      name: bad-website
      rules:
      - name: checker
        patterns:
        - context: url
          key: pattern
          op: regex
          value: .+badsite.+
kind: List
metadata: {}
```
3) Create job as below
```
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: badsite-cron
  namespace: example
  labels:
    app: badsite
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: badsite
        spec:
          containers:
          - name: badjob
            image: curlimages/curl 
            imagePullPolicy: IfNotPresent
            args: 
              - |
                sleep 5
                curl https://badsite.blah.net 
            command: ["/bin/sh", "-c"]
          restartPolicy: OnFailure
```

The curl will be blocked
4) Run with  no sleep, or a sleep of 4 seconds and below
```
 spec:
          containers:
          - name: badjob
            image: curlimages/curl 
            imagePullPolicy: IfNotPresent
            args: 
              - |
                sleep 1
                curl https://badsite.blah.net 
```

The curl is no longer blocked, even if a default rule is used to block all pod to external communications.

5) The behaviour can also be seen on the first run of the following pod
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: badsite 
  name: curlpodbadsite
  namespace: example
spec:
  containers:
   - args: 
       - |
         #         sleep 10
         curl https://badsite.blah.net 
     command: ["/bin/sh", "-c"]
     image: curlimages/curl
     imagePullPolicy: Always
     name: badsite
```

Subsequent runs do block

**Expected behavior**
I would expect if a container is in a group, that it is identified quickly enough to enforce rules.
