### ISSUE TITLE
Support grace period when accepting specific vulnerabilities

### ISSUE THREAD

**Issue by lentus** [neuvector/neuvector#1829]
**Is your feature request related to a problem? Please describe.**
Using vulnerability profiles it is currently possible to:
- accept specific vulnerabilities, in general or for certain images and/or namespaces
- accept recent vulnerabilities (with or without available fix), in general or for certain images and/or namespaces

However, it is currently not possible to accept a specific vulnerability for a certain period. This is a feature that many vulnerability scanners, such as Dependency Check, Trivy and ZAP, do support.

**Describe the solution you'd like**
I would like to be able to accept specific vulnerabilities for a limited time, so that I can provide a grace period for application developers to fix a given vulnerability.

Ideally this would be implemented using an `until` field in the vulnerability profile CRD:
```yaml
apiVersion: neuvector.com/v1
kind: NvVulnerabilityProfile
metadata:
  name: default
spec:
  profile:
    entries:
      - comment: Suppression for image with grace period
         name: CVE-xxxx-yyyyy
         until: 2025-02-20
         domains: []
         images:
           - <image-name>
```

**Describe alternatives you've considered**
Another simpler solution might be to enable the use of the `days` field when accepting a specific vulnerability. This could then be used to specify a grace period using a number of days from when the vulnerability was published. 

**Additional context**
None
