### ISSUE TITLE
duplicate rule entries

### ISSUE THREAD

**Issue by DrackThor** [neuvector/neuvector#1856]
**Environment**
Platform: RKE2
Kubernetes/Platform Version(s): v1.30.4 +rke2r1

**Describe the bug**
It is currently possible to have duplicate network and process rules (maybe also file and response, didn't check yet).
This leads to confusion for our users and overhead on the admin team.

**To Reproduce**
1. install NV from scratch and add some workload to the cluster
2. NV will identify groups and learn rules
3. export the learned groups in monitor mode
4. import the exported groups
5. transform the exported groups to CRDs and apply them
6. in the group {network/process} rule tabs you will see duplicates. once for the CRD rules, once for the user-created

**Expected behavior**
We would propose to implement a duplicate checking mechanism to..
- "prevent" learning rules which already exist by CRD
- ignore/skip user-created (or imported) rules that already exist
- ignore/skip/fail rules created by CRDs that already exist

proposed priority hierarchy:
- CRD
- user created
- learned

**Screenshots**
![Image](https://github.com/user-attachments/assets/7ee473e3-a73b-4886-9ef9-b8e36f6de1e8)

**Additional context**
I think using a combination of `action`, `applications`, `ports` and `selector.criteria` do identify unique network rules would make sense. For processes all attributes can be used as unique key.

```yaml
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  creationTimestamp: null
  name: nv.asdf.kube-system
  namespace: kube-system
spec:
  process:
    - action: allow
      allow_update: false
      name: descheduler
      path: /bin/descheduler
    - action: allow
      allow_update: false
      name: pause
      path: /pause
  egress:
    - action: allow
      applications:
        - any
      name: nv.kube-apiserver.kube-system-egress-26
      ports: tcp/6443
      priority: 0
      selector:
        comment: ""
        criteria:
          - key: domain
            op: "="
            value: kube-system
          - key: service
            op: "="
            value: kube-apiserver.kube-system
        name: nv.kube-apiserver.kube-system
        original_name: ""
```
