### ISSUE TITLE
group export (network) rule IDs change

### ISSUE THREAD

**Issue by DrackThor** [neuvector/neuvector#1857]
**Environment**
Platform: RKE2
Kubernetes/Platform Version(s): v1.30.4 +rke2r1 

**Describe the bug**
When you export groups via the UI (groups tab, select some groups, export group policy), the exported YAML will differ, depending on the order (and probably also amount) of groups.
Well yes, obviously it does, but there is one distinct problem we face: the order of exported groups affects the `name` of `ingress/egress` rules.
Meaning: depending on the order of groups (as selected in the GUI), the names of `spec.egress[].name` will differ, for the same rule.

As we use a gitops approach for defining and managing groups, this can badly interfere with our workflow.

- we learn groups/rules on a test cluster
- export the rules in monitor/protect mode
- deploy them via gitops tools to higher stages

depending on the order (maybe also amount?) of groups we export, the rule names differ, which will pontentially change our gitops config unnecessarily... if no (real) change happened to an exported group. 

**To Reproduce**
1. learn some groups/rules in NV
2. go to the groups tab
3. sort by "name" and select all groups of one namespace
4. export in monitor mode
5. re-sort the list in the UI by name, different order
6. again export all groups of one namespace in monitor mode
7. compare the exported yamls - focus on the comparison of the same group in both files

Example:

```yaml
# first export
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    creationTimestamp: null
    name: nv.argocd-server.argocd
    namespace: argocd
  spec:
    dlp:
      settings: []
      status: false
    egress:
    - action: allow
      applications:
      - any
      name: nv.kube-apiserver.kube-system-egress-0 # <- see ID 0
      ports: tcp/6443
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: kube-system
        - key: service
          op: =
          value: kube-apiserver.kube-system
        name: nv.kube-apiserver.kube-system
        original_name: ""
# omitted rest of the file
```

```yaml
# second export
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    creationTimestamp: null
    name: nv.argocd-server.argocd
    namespace: argocd
  spec:
    dlp:
      settings: []
      status: false
    egress:
    - action: allow
      applications:
      - any
      name: nv.kube-apiserver.kube-system-egress-13 # <- see ID 13
      ports: tcp/6443
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: domain
          op: =
          value: kube-system
        - key: service
          op: =
          value: kube-apiserver.kube-system
        name: nv.kube-apiserver.kube-system
        original_name: ""
# omitted rest of the file
```

**Expected behavior**
 
Ingress/Egress rules should have the same `name`, no matter in which order/amount they are exported.

**Screenshots**

Should be clear from YAMLs.

**UI Issue**
no.

**Additional context**

I guess in code it would probably work if one changed from a simple counter index based approach, to using an internal unique rule ID?

I guess some changes in `func exportAttachRule()` [here](https://github.com/neuvector/neuvector/blob/bdbc211b02d8ebad70908918530c5f30c8e3b3a8/controller/rest/crdsecurityrule.go#L3562), `func handlerGroupCfgExport()` [here](https://github.com/neuvector/neuvector/blob/bdbc211b02d8ebad70908918530c5f30c8e3b3a8/controller/rest/crdsecurityrule.go#L3778) and specifying the `rule.ID` ([see](https://github.com/neuvector/neuvector/blob/bdbc211b02d8ebad70908918530c5f30c8e3b3a8/controller/api/apis.go#L1307)) instead of a counter index could do the trick.
I guess this could lead to unique and non-changing rule IDs in the exported yamls.
I'm definitely not a golang developer, nor neuvector contributor, so I'm relying on help from here on 😄
