### ISSUE TITLE
NvSecurityRule CRD object dryrun is denied by the neuvector-validating-crd-webhook

### ISSUE THREAD

**Issue by oleksandr9379992** [neuvector/neuvector#649]
**Environment**
Platform: AKS
Kubernetes/Platform Version(s): 1.24.9
Neuvector Helm Chart: 2.4.2

**Describe the bug**
When I try to run `kubectl apply -f .\neuvector-securityrule.yaml --dry-run=server` I am receiving error:
```
Error from server: error when creating ".\\neuvector-securityrule.yaml": admission webhook "neuvector-validating-crd-webhook.neuvector.svc" denied the request:  CREATE denied in dry-run
```
Without dry-run the apply works:
```
kubectl apply -f .\neuvector-securityrule.yaml 
[nvsecurityrule.neuvector.com/nv.ingress-nginx-infra-controller.ingress-nginx-infra](https://nvsecurityrule.neuvector.com/nv.ingress-nginx-infra-controller.ingress-nginx-infra) created
```
**To Reproduce**
1. Create the file `neuvector-securityrule.yaml ` with the following content:
```
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: nv.ingress-nginx-infra-controller.ingress-nginx-infra
  namespace: ingress-nginx-infra
spec:
  dlp:
    settings: []
    status: true
  egress: []
  file: []
  ingress:
  - action: allow
    applications:
    - HTTP
    - SSL
    name: nv.ingress-nginx-infra-controller.ingress-nginx-infra-ingress-0
    ports: any
    priority: 0
    selector:
      comment: ""
      criteria: []
      name: nodes
      original_name: ""
  process:
  - action: allow
    allow_update: false
    name: dumb-init
    path: /usr/bin/dumb-init
  - action: allow
    allow_update: false
    name: nginx
    path: /usr/local/nginx/sbin/nginx
  - action: allow
    allow_update: false
    name: nginx-ingress-controller
    path: /nginx-ingress-controller
  - action: allow
    allow_update: false
    name: pause
    path: /pause
  process_profile:
    baseline: zero-drift
  target:
    policymode: Protect
    selector:
      comment: ""
      criteria:
      - key: service
        op: =
        value: ingress-nginx-infra-controller.ingress-nginx-infra
      - key: domain
        op: =
        value: ingress-nginx-infra
      name: nv.ingress-nginx-infra-controller.ingress-nginx-infra
      original_name: ""
  waf:
    settings: []
    status: true
```
2. Run `kubectl apply -f .\neuvector-securityrule.yaml --dry-run=server`
3. See error:
```
Error from server: error when creating ".\\neuvector-securityrule.yaml": admission webhook "neuvector-validating-crd-webhook.neuvector.svc" denied the request:  CREATE denied in dry-run
```

**Expected behavior**
The dryrun needs to be successful, else I am not able to deploy CRD using FLUX V2 on AKS.

**Screenshots**
N/A

**UI Issue**
N/A

**Additional context**
N/A
