### ISSUE TITLE
Neuvector 5.1.2 compliance template is empty in GUI

### ISSUE THREAD

**Issue by megabreit** [neuvector/neuvector#728]
**Environment**
Platform: k3s 1.24.11+k3s1 with nginx ingress, neuvector 5.1.2, Ubuntu 22.04

**Describe the bug**
Compliance template in GUI is empty

**To Reproduce**
Just install neuvector 5.1.2 and go to Compliance template menu
```
apiVersion: v1
kind: Namespace
metadata:
  name: neuvector
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: neuvector
  namespace: kube-system
spec:
  chart: core
  repo: https://neuvector.github.io/neuvector-helm/
  targetNamespace: neuvector
  set:
  valuesContent: |-
    registry: docker.io
    tag: 5.1.2
    admissionwebhook:
      type: ClusterIP
    controller:
      enabled: true
      federation:
        managedsvc:
          ingress:
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
              nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
            enabled: false
            host: null
            path: /
            tls: true
          type: ClusterIP
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        enabled: true
        host: neuvector-api.example.com
        path: /
        secretName: null
        tls: true
      ranchersso:
        enabled: false
      apisvc:
        type: ClusterIP
      pvc:
        enabled: true
        accessModes:
          - ReadWriteOnce
      replicas: 1
      configmap:
        enabled: true
        data:
          userinitcfg.yaml: |
            always_reload: true
            users:
            - Fullname: admin
              Password: adminpassword
              Role: admin
              Timeout: 3600
          passwordprofileinitcfg.yaml: |
            always_reload: true
            active_profile_name: default
            pwd_profiles:
            - name: default
              comment: default from configMap
              min_len: 10
          sysinitcfg.yaml: |
            always_reload: true
            Cluster_Name: concon
    crdwebhook:
      enabled: true
      type: ClusterIP
    k3s:
      enabled: true
      runtimePath: /run/k3s/containerd/containerd.sock
    manager:
      enabled: true
      env:
        ssl: true
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        enabled: true
        host: neuvector.example.com
        path: /
        tls: false
      svc:
        type: ClusterIP
    cve:
      scanner:
        replicas: 1
```
It's displayed with the same yaml, just version set to 5.1.1 (or earlier). There is no difference if updated from 5.1.1 or newly installed.
It seems just to be a display issue, in other parts of the application compliance data is visible.

**Expected behavior**
Compliance templates are displayed
