### ISSUE TITLE
Defining OCP internal registry & Authenticated by Token

### ISSUE THREAD

**Issue by raif-ahmed** [neuvector/neuvector#761]
**Environment**
OpenShift 4.11

**Describe the bug**
the Web Ui truncate the OCP Service account (SA) token, to overcome this issue i have to use the Rest API.

**To Reproduce**
create a service account with needed rolebindings 

```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: image-scanner
  namespace: neuvector
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'neuvector-image-auditor'
subjects:
  - kind: ServiceAccount
    name: image-scanner
    namespace: neuvector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-auditor'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'neuvector-cluster-reader'
subjects:
  - kind: ServiceAccount
    name: image-scanner
    namespace: neuvector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'cluster-reader'
```  
extract the token to use in the UI
```
_REGISTRY_TOKEN=$(oc get secret $(oc describe sa/image-scanner -n neuvector | grep Tokens: | awk '/Tokens:[[:space:]]/ { print $2 }') -n neuvector -o custom-columns=NAME:.data.token --no-headers | base64 -d)

echo $_REGISTRY_TOKEN
```

Try to Add registry
Type: Openshift Registry
Registry: https://image-registry.openshift-image-registry.svc:5000
choose: Authenticated by Token
Try to paste the token, you will find it is truncated 

**Additional context**
I can overcome this issue y using the Rest API

```
curl -X POST -k  "https://$_controllerIP_:$_controllerRESTAPIPort_/v1/scan/registry" \
   -H "X-Auth-Token: $_TOKEN_" \
   -H 'Content-Type: application/json' \
   -d '{"config":{"name":"myregistry","registry":"https://image-registry.openshift-image-registry.svc:5000/","registry_type":"OpenShift Registry","filters":["*"],"auth_token":"$_REGISTRY_TOKEN","auth_with_token":true,"repo_limit":200,"rescan_after_db_update":true,"scan_layers":false,"tag_limit":1,"schedule":{"schedule":"manual","interval":5}}}'
```
