### ISSUE TITLE
CRD admission rules with a name other than "local" are ignored

### ISSUE THREAD

**Issue by megabreit** [neuvector/neuvector#783]
**Environment**
Platform: k3s
Kubernetes/Platform Version(s): k3s 1.24.11, Neuvector 5.1.1, Ubuntu 20.04

**Describe the bug**
Admission controller rules which are applied as CR (nvadmissioncontrolsecurityrule) with a metadata.name other than "local" are not visible in the Neuvector GUI and the rules are ignored by the admission controller.
Multiple CRD rules can be created, they all seem to be ignored by the admission controller.
The only way to create CRD admission rules is to create **EXACTLY ONE** rule with the name "local".
There is no documentation about this behavior on https://open-docs.neuvector.com.

**To Reproduce**
kubectl apply this yaml:
```
apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local1
spec:
  config:
    client_mode: service
    enable: true
    mode: protect
  rules:
  - action: deny
    comment: deny forbidden
    criteria:
    - name: namespace
      op: containsAny
      path: namespace
      value: forbidden
```
`kubectl run sleep -n forbidden alpine:latest --command sleep 99999999`
Pod creation in namespace forbidden is allowed.

**Expected behavior**
Either
- Rule should be visible in the GUI
- Rule should be active

or
- It should not be possible to apply more than one or invalid rules

- The behavior (either way) should be documented
