### ISSUE TITLE
Admission Controls fails to validate

### ISSUE THREAD

**Issue by 0Styless** [neuvector/neuvector#886]
**Environment**
Platform: Rancher
Kubernetes/Platform Version(s): v1.24.13+rke2r1 / NeuVector 5.1.3

**Describe the bug**
Not all AdmissionControlls seems to work as expected, especially when you try to validate a custom path inside securityContext.

**To Reproduce**
1. Create a new admission rule, for example:
```yaml
apiVersion: neuvector.com/v1
kind: NvAdmissionControlSecurityRule
metadata:
  name: local
spec:
  config:
    client_mode: service
    enable: true
    mode: monitor
  rules:
  - action: deny
    comment: require-readonly-filesystem
    criteria:
    - name: customPath
      op: =
      path: item.spec.initContainers[_].securityContext.readOnlyRootFilesystem
      template_kind: podTemplate
      type: customPath
      value: "false"
      value_type: boolean
    - name: customPath
      op: =
      path: item.spec.containers[_].securityContext.readOnlyRootFilesystem
      template_kind: podTemplate
      type: customPath
      value: "false"
      value_type: boolean
```
2. Create a example k8s deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: hub.docker.com/library/nginx:1.14.2
          securityContext:
            readOnlyFileSystem: false
          ports:
            - containerPort: 80
```
3. In the UI go to Admission Control and try to validate the deployment.yaml with "Configuration Assessment"
4. There is no issue detected with this deployment.yaml

**Expected behavior**
deployment.yaml should be denied

**Additional context**
This seems to appear with various custom path criterias, like:
* `item.spec.initContainers[_].securityContext.runAsGroup <= 2000`
* `item.spec.containers[_].securityContext.runAsNonRoot = false`
* `item.spec.containers[_].securityContext.capabilities.add exists`
* `item.spec.initContainers[_].ports[_].hostPort exists`
